### ISSUE TITLE
Add meetup icon w/ link

### ISSUE THREAD

**Issue by jaredrhodes** [toledowebprofessionals/toledowebprofessionals.github.io#6]

**Comment by jaredrhodes** [comment]
@shrinkray @danpaquette made a pull request on a new branch, develop. Screencap of the update if you don't feel like pulling it down. Just didn't want to push it out live without a second pair of eyes.

**Comment by shrinkray** [comment]
Work is in 'intro-message' branch. If no objections I will merge changes to master.

**Comment by shrinkray** [comment]
Added Meetup icon to site & pushed to master.
