### ISSUE TITLE
Fix nav jutting off right side on Chrome mobile (Android)

### ISSUE THREAD

**Issue by jaredrhodes** [toledowebprofessionals/toledowebprofessionals.github.io#7]
On page load, the main content fits the screen width but the navigation width is larger. The hamburger is not visible without scrolling right. There is some extra whitespace when scrolling right.

**Comment by danpaquette** [comment]
Can someone QA this fix? Ref: 5f273281b04bd5ee35c41460f55b0fe9a6b4298a

**Comment by jaredrhodes** [comment]
Yes, fixed on Chrome/Android.
