### ISSUE TITLE
Call for Sponsors - Call to Action

### ISSUE THREAD

**Issue by cwammes** [toledowebprofessionals/toledowebprofessionals.github.io#8]
Need to direct Sponsors on how to contact us, email should work.

**Comment by jaredrhodes** [comment]
Has been discussion on Slack about using Wufoo also.

**Comment by shrinkray** [comment]
I added a written message in the content directing someone to send an email. The email I used is obfuscated. Jared suggests using WooFu forms which would be useful in the landing section.
