### ISSUE TITLE
Meta data

### ISSUE THREAD

**Issue by cwammes** [toledowebprofessionals/toledowebprofessionals.github.io#9]
Add meta data to this site:

Apple Meta Information
apple-touch-icon-precomposed

Open Graph Protocol 
og:title
og:site_name
og:description
og:image
og:url
og:type
og:locale

Twitter Cards Markup
twitter:card
twitter:title
twitter:image>
twitter:description
twitter:site
twitter:site:id

**Comment by shrinkray** [comment]
I pushed an update in my last commit which includes the missing meta. Cheers.
